name: "🚀 publish"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: 🚀 publish
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v2.1.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      - name: 🟢 node
        uses: actions/setup-node@v1.4.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: 🚀 publish
        run: npm publish --access public
        working-directory: my-pkg
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
